upgrade to dkml-workflows.1.2.0

diff --git a/ci/setup-dkml/gh-linux/pre/action.yml b/ci/setup-dkml/gh-linux/pre/action.yml
--- a/ci/setup-dkml/gh-linux/pre/action.yml
+++ b/ci/setup-dkml/gh-linux/pre/action.yml
@@ -259,6 +259,10 @@ runs:
         setup_WORKSPACE=$1
         shift
 
+        if [ -x /usr/bin/cygpath ]; then
+            setup_WORKSPACE=$(/usr/bin/cygpath -au "$setup_WORKSPACE")
+        fi
+
         # ------------------------ Functions ------------------------
 
         # shellcheck source=./common-values.sh
@@ -330,6 +334,10 @@ runs:
 
         # dkml-runtime-distribution
 
+        #   For 'Diagnose Visual Studio environment variables (Windows)' we need dkml-runtime-distribution
+        #   so that 'Import-Module Machine' and 'Get-VSSetupInstance' can be run.
+        #   The version doesn't matter too much, as long as it has a functioning Get-VSSetupInstance.
+        #   commit 1a3ec82dd851751a95e6a4797387a8163c51520e = tag v0.4.0-prerel20
         case "$dkml_host_abi" in
         windows_*)
             section_begin checkout-dkml-runtime-distribution 'Checkout dkml-runtime-distribution'
@@ -347,17 +355,18 @@ runs:
         # Constants
         SHA512_DEVNULL='cf83e1357eefb8bdf1542850d66d8007d620e4050b5715dc83f4a921d36ce9ce47d0d13c5d85f2b0ff8318d2877eec2f63b931bd47417a81a538327af927da3e'
         #   Edited by https://gitlab.com/diskuv/diskuv-ocaml/contributors/release.sh
-        DEFAULT_DISKUV_OPAM_REPOSITORY_TAG=cc9518fa5630bfbe24d4c5e0e2cc29af513037ce
+        DEFAULT_DISKUV_OPAM_REPOSITORY_TAG=cdf6463c5c3c7ca37bc798e17929bff1c481bfdd
         # Constants
-        #   Should be edited by release.sh, but ...
-        #   Can't be 1.0.0 or later until https://github.com/ocaml/opam-repository/pull/21704 ocaml-option-32bit
-        #   can come back in.
-        DKML_VERSION=0.4.0
+        DKML_VERSION=1.1.0
 
         setup_WORKSPACE_VARNAME=$1
         shift
         setup_WORKSPACE=$1
         shift
+
+        if [ -x /usr/bin/cygpath ]; then
+            setup_WORKSPACE=$(/usr/bin/cygpath -au "$setup_WORKSPACE")
+        fi
 
         # ------------------ Variables and functions ------------------------
 
@@ -420,6 +429,7 @@ runs:
         CONF_DKML_CROSS_TOOLCHAIN=${CONF_DKML_CROSS_TOOLCHAIN:-}
         SECONDARY_SWITCH=${SECONDARY_SWITCH:-}
         MANYLINUX=${MANYLINUX:-}
+        DKML_HOME=${DKML_HOME:-}
         VERBOSE=${VERBOSE:-}
         .
         -------------------
@@ -460,7 +470,6 @@ runs:
         PIN_DIGESTIF=${PIN_DIGESTIF}
         PIN_DKML_APPS=${PIN_DKML_APPS}
         PIN_DUNE=${PIN_DUNE}
-        PIN_DUNE_CONFIGURATOR=${PIN_DUNE_CONFIGURATOR}
         PIN_OCAMLBUILD=${PIN_OCAMLBUILD}
         PIN_OCAMLFIND=${PIN_OCAMLFIND}
         PIN_OCP_INDENT=${PIN_OCP_INDENT}
@@ -810,6 +819,7 @@ runs:
 
             # ---------------
             # Create Opam troubleshooting script
+            #   Dump logs modified within the last 4 hours
             # ---------------
 
             cat >.ci/sd4/troubleshoot-opam.sh <<EOF
@@ -817,8 +827,13 @@ runs:
         set -euf
         OPAMROOT=\$1
         shift
+        if find . -maxdepth 0 -mmin -240 2>/dev/null >/dev/null; then
+            FINDARGS="-mmin -240" # is -mmin supported? BSD (incl. macOS), MSYS2, GNU
+        else
+            FINDARGS="-mtime -1" # use 1 day instead. Solaris
+        fi
         printf "\n\n========= [START OF TROUBLESHOOTING] ===========\n\n" >&2
-        find "\$OPAMROOT"/log -mindepth 1 -maxdepth 1 -name "*.out" ! -name "log-*.out" ! -name "ocaml-variants-*.out" | while read -r dump_on_error_LOG; do
+        find "\$OPAMROOT"/log -mindepth 1 -maxdepth 1 \$FINDARGS -name "*.out" ! -name "log-*.out" ! -name "ocaml-variants-*.out" | while read -r dump_on_error_LOG; do
             dump_on_error_BLOG=\$(basename "\$dump_on_error_LOG")
             printf "\n\n========= [TROUBLESHOOTING] %s ===========\n\n" "\$dump_on_error_BLOG" >&2
             awk -v BLOG="\$dump_on_error_BLOG" '{print "[" BLOG "]", \$0}' "\$dump_on_error_LOG" >&2
@@ -1223,6 +1238,7 @@ runs:
                 # Validate OCAML_COMPILER (OCAML_COMPILER specified)
                 case "${OCAML_COMPILER:-}" in
                 4.12.1) true ;;
+                4.14.0) true ;;
                 *)
                     echo "OCAML_COMPILER version ${OCAML_COMPILER:-} is not supported" >&2
                     exit 109
@@ -1282,7 +1298,7 @@ runs:
             opamrun pin add --switch "$do_pins_NAME"  --yes --no-action -k version digestif "${PIN_DIGESTIF}"
             opamrun pin add --switch "$do_pins_NAME"  --yes --no-action -k version dkml-apps "${PIN_DKML_APPS}"
             opamrun pin add --switch "$do_pins_NAME"  --yes --no-action -k version dune "${PIN_DUNE}"
-            opamrun pin add --switch "$do_pins_NAME"  --yes --no-action -k version dune-configurator "${PIN_DUNE_CONFIGURATOR}"
+            opamrun pin remove --switch "$do_pins_NAME"  --yes --no-action dune-configurator # this used to be pinned, so any cached opamroot needs it unpinned
             opamrun pin add --switch "$do_pins_NAME"  --yes --no-action -k version ocamlbuild "${PIN_OCAMLBUILD}"
             opamrun pin add --switch "$do_pins_NAME"  --yes --no-action -k version ocamlfind "${PIN_OCAMLFIND}"
             opamrun pin add --switch "$do_pins_NAME"  --yes --no-action -k version ocp-indent "${PIN_OCP_INDENT}"
@@ -1379,12 +1395,32 @@ runs:
         do_setenv() {
             do_setenv_SWITCH=$1
             shift
+            section_begin "setenv-$do_setenv_SWITCH" "Set opam option for $do_setenv_SWITCH switch"
             opamrun option --switch "$do_setenv_SWITCH" setenv > ".ci/sd4/setenv.$do_setenv_SWITCH.txt"
             if ! grep -q '\(^|\[\)DiskuvOCamlVarsVersion ' ".ci/sd4/setenv.$do_setenv_SWITCH.txt"; then
                 opamrun option --switch "$do_setenv_SWITCH" setenv+='DiskuvOCamlVarsVersion = "2"'
             fi
             if ! grep -q '\(^|\[\)DiskuvOCamlVersion ' ".ci/sd4/setenv.$do_setenv_SWITCH.txt"; then
                 opamrun option --switch "$do_setenv_SWITCH" setenv+="DiskuvOCamlVersion = \"$DKML_VERSION\""
+            fi
+            if [ "$do_setenv_SWITCH" = dkml ] && [ -n "${DKML_HOME:-}" ]; then
+              do_setenv_DKMLHOME_ESCAPED="$DKML_HOME"
+              do_setenv_USRBIN_ESCAPED="$DKML_HOME/usr/bin"
+              do_setenv_BIN_ESCAPED="$DKML_HOME/bin"
+              if [ -x /usr/bin/cygpath ]; then
+                do_setenv_DKMLHOME_ESCAPED=$(/usr/bin/cygpath -aw "$do_setenv_DKMLHOME_ESCAPED" | sed 's/\\/\\\\/g')
+                do_setenv_USRBIN_ESCAPED=$(/usr/bin/cygpath -aw "$do_setenv_USRBIN_ESCAPED" | sed 's/\\/\\\\/g')
+                do_setenv_BIN_ESCAPED=$(/usr/bin/cygpath -aw "$do_setenv_BIN_ESCAPED" | sed 's/\\/\\\\/g')
+              fi
+              if ! grep -q '\(^|\[\)DiskuvOCamlHome ' ".ci/sd4/setenv.$do_setenv_SWITCH.txt"; then
+                  opamrun option --switch "$do_setenv_SWITCH" setenv+="DiskuvOCamlHome = \"$do_setenv_DKMLHOME_ESCAPED\""
+              fi
+              if ! grep -q '\(^|\[\)DiskuvOCamlBinaryPaths ' ".ci/sd4/setenv.$do_setenv_SWITCH.txt"; then
+                  opamrun option --switch "$do_setenv_SWITCH" setenv+="DiskuvOCamlBinaryPaths = \"$do_setenv_USRBIN_ESCAPED;$do_setenv_BIN_ESCAPED\""
+              fi
+              if ! grep -q '\(^|\[\)DiskuvOCamlDeploymentId ' ".ci/sd4/setenv.$do_setenv_SWITCH.txt"; then
+                  opamrun option --switch "$do_setenv_SWITCH" setenv+="DiskuvOCamlDeploymentId = \"setup-dkml-switch-$do_setenv_SWITCH\""
+              fi
             fi
             case "${dkml_host_abi}" in
             windows_*)
@@ -1400,6 +1436,7 @@ runs:
                     opamrun option --switch "$do_setenv_SWITCH" setenv+="DiskuvOCamlMSYS2Dir = \"$MSYS2_DIR_NATIVE_ESCAPED\""
                 fi
             esac
+            section_end "setenv-$do_setenv_SWITCH"
         }
         if [ "${SECONDARY_SWITCH:-}" = "true" ]; then
             do_setenv two
@@ -1566,7 +1603,7 @@ runs:
       shell: bash
       run: |
         set -x
-        echo '317446-${{ inputs.FDOPEN_OPAMEXE_BOOTSTRAP }}-${{ steps.full_matrix_vars.outputs.dkml_host_abi }}-${{ steps.full_matrix_vars.outputs.opam_abi }}-${{ steps.full_matrix_vars.outputs.bootstrap_opam_version }}' > .ci/sd4/cachekey.opam.binaries
+        echo 'a8f507-${{ inputs.FDOPEN_OPAMEXE_BOOTSTRAP }}-${{ steps.full_matrix_vars.outputs.dkml_host_abi }}-${{ steps.full_matrix_vars.outputs.opam_abi }}-${{ steps.full_matrix_vars.outputs.bootstrap_opam_version }}' > .ci/sd4/cachekey.opam.binaries
         echo '${{ steps.full_matrix_vars.outputs.abi_pattern }}-${{ steps.full_matrix_vars.outputs.vsstudio_arch }}-${{ steps.full_matrix_vars.outputs.vsstudio_hostarch }}-${{ steps.full_matrix_vars.outputs.vsstudio_dir }}-${{ steps.full_matrix_vars.outputs.vsstudio_vcvarsver }}-${{ steps.full_matrix_vars.outputs.vsstudio_winsdkver }}-${{ steps.full_matrix_vars.outputs.vsstudio_msvspreference }}-${{ steps.full_matrix_vars.outputs.vsstudio_cmakegenerator }}' > .ci/sd4/cachekey.vsstudio
         echo '${{ inputs.OCAML_COMPILER }}-${{ inputs.DISKUV_OPAM_REPOSITORY }}-${{ inputs.DKML_COMPILER }}-${{ inputs.CONF_DKML_CROSS_TOOLCHAIN }}' > .ci/sd4/cachekey.ci.inputs
 
@@ -1664,7 +1701,7 @@ runs:
         MANYLINUX:                        "${{ inputs.MANYLINUX }}"
 
         # autogen from global_env_vars.
-        DEFAULT_DKML_COMPILER: '4.12.1-v1.0.2'
+        DEFAULT_DKML_COMPILER: '4.14.0-v1.1.0-prerel15'
         PIN_BASE: 'v0.14.3'
         PIN_BIGSTRINGAF: '0.8.0'
         PIN_CORE_KERNEL: 'v0.14.2'
@@ -1672,16 +1709,15 @@ runs:
         PIN_CTYPES: '0.19.2-windowssupport-r4'
         PIN_CURLY: '0.2.1-windows-env_r2'
         PIN_DIGESTIF: '1.0.1'
-        PIN_DUNE: '2.9.3+shim.1.0.2~r0'
-        PIN_DUNE_CONFIGURATOR: '2.9.3'
-        PIN_DKML_APPS: '1.0.1'
+        PIN_DUNE: '3.6.2'
+        PIN_DKML_APPS: '1.1.0'
         PIN_OCAMLBUILD: '0.14.0'
         PIN_OCAMLFIND: '1.9.1'
         PIN_OCP_INDENT: '1.8.2-windowssupport'
         PIN_PPX_EXPECT: 'v0.14.1'
         PIN_PTIME: '0.8.6-msvcsupport'
         PIN_TIME_NOW: 'v0.14.0'
-        PIN_WITH_DKML: '1.0.1'
+        PIN_WITH_DKML: '1.1.0'
       run: |
         sh .ci/sd4/run-setup-dkml.sh GITHUB_WORKSPACE "$GITHUB_WORKSPACE"
 
